services:
  prediction:
    build: .
    environment:
      - MODEL_PATH=/app/data/models/baseline-149.onnx
      - UPLOAD_FOLDER=/app/data/upload/
    ports:
      - "5000:5000"
    volumes:
      - ../data/models:/app/data/models
